Log: Use "%s" in log() calls without compile-time constants
Building the LFS plugin as of 1f4c412 with gerrit on branch stable-3.6
(a6830e6fdb) fails with

    error: [FloggerLogString] Arguments to log(String) must be
        compile-time constants or parameters annotated with
        @CompileTimeConstant. If possible, use Flogger's formatting log methods
        instead.

Found while working on bug 16863[1].

[1] https://bugs.chromium.org/p/gerrit/issues/detail?id=16863

Change-Id: Iaac2e4272aa9c10e7b7eed71b482517babe97ab0