Update patch set 7
Patch Set 7: Verified-1

This passes in Eclipse, but on the command line it fails with:

  expected:<...8-01-31T12:26:45.582[Z]> but was:<...8-01-31T12:26:45.582[+00:00]>

It seems in Eclipse it's using a +9 timezone (my current local time zone) instead of UTC:

  2018-01-31T21:29:15.289+09:00

and both joda time and java time are producing the same string.

Patch-set: 7
Reviewer: Gerrit User 1011123 <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1