Update patch set 3
Patch Set 3: Verified-1 Code-Review-1

This removed the @jgit_lfs//jar dependency, which causes the test compilation to fail:

  error: [strict] Using type org.eclipse.jgit.lfs.lib.LongObjectId from an indirect dependency

Patch-set: 3
Reviewer: Gerrit User 1011123 <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1
Label: Code-Review=-1