Update patch set 1
Patch Set 1:

Unrelated to this change, but this is failing to build here in standalone mode with Bazel 0.18.0rc4:

  ERROR: /home/davido/projects/lfs/BUILD:9:1: Executing genrule //:lfs failed (Exit 1)
  Target //:lfs failed to build

The reason is that tools/bazel.rc should be moved to .bazelrc.

Should we do here what was done in other plugins, e.g.: [1].

[1] https://gerrit-review.googlesource.com/c/plugins/oauth/+/192436

Patch-set: 1
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>