Update patch set 2
Patch Set 2: Verified-1

Works in standalone mode, but fails in-tree because it doesn't like the jgit-lfs definitions.

  ERROR: /Users/dpursehouse/git/gerrit/plugins/lfs/BUILD:3:1: no such target '//lib/jgit:jgit-http-apache': target 'jgit-http-apache' not declared in package 'lib/jgit' defined by /Users/dpursehouse/git/gerrit/lib/jgit/BUILD and referenced by '//plugins/lfs:lfs__plugin'.

Patch-set: 2
Label: Verified=-1