Remove ambiguous Truth8.assertThat
Truth8 is deprecated and Truth.assertThat is already imported statically
resulting in:

  error: reference to assertThat is ambiguous

Change-Id: Id36412324142964fa3b8826623cda053bec193b2